//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICarFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gen()
        {
            this.loan = new HashSet<loan>();
        }
    
        public int gencode { get; set; }
        public string genname { get; set; }
        public string genyear { get; set; }
        public Nullable<decimal> gencost { get; set; }
        public string gendetail { get; set; }
        public Nullable<int> gencar { get; set; }
    
        public virtual car car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan> loan { get; set; }
    }
}
