//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICarFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        public string recode { get; set; }
        public Nullable<int> reloan { get; set; }
        public Nullable<System.DateTime> redate { get; set; }
        public Nullable<decimal> remoney { get; set; }
        public Nullable<decimal> rerecive { get; set; }
        public Nullable<decimal> rechange { get; set; }
        public string remem { get; set; }
    
        public virtual loan loan { get; set; }
    }
}
