//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICarFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customer : loan
    {
        public int loancode { get; set; }
        public string memname { get; set; }
        public string memlname { get; set; }
        public string memtel { get; set; }
        public Nullable<decimal> loanmoney { get; set; }
        public Nullable<int> loanmonth { get; set; }
        public Nullable<decimal> loadpermonth { get; set; }
        public string carbrand { get; set; }
        public string genname { get; set; }
    }
}
