//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICarFinance
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Car
    {
        public int gencode { get; set; }
        public string carbrand { get; set; }
        public string genname { get; set; }
        public string genyear { get; set; }
        public Nullable<decimal> gencost { get; set; }
        public string gendetail { get; set; }
    }
}
