//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarFinance5917Entities : DbContext
    {
        public CarFinance5917Entities()
            : base("name=CarFinance5917Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<gen> gen { get; set; }
        public virtual DbSet<In_Ex> In_Ex { get; set; }
        public virtual DbSet<loan> loan { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<receipt> receipt { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<View_Car> View_Car { get; set; }
        public virtual DbSet<View_Customer> View_Customer { get; set; }
    }
}
